# permissions for end users to edit images.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: orc
    app.kubernetes.io/managed-by: kustomize
  name: image-editor-role
rules:
- apiGroups:
  - openstack.k-orc.cloud
  resources:
  - images
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - openstack.k-orc.cloud
  resources:
  - images/status
  verbs:
  - get
