namespace: vexxhost
name: kubernetes
version: 3.0.1
readme: README.md
authors:
  - Mohammed Naser <mnaser@vexxhost.com>
description: Ansible collection for deploying Kubernetes clusters
license:
  - GPL-3.0-or-later
dependencies:
  ansible.posix: '>=2.1.0'
  community.crypto: '>=3.2.0'
  community.general: '>=12.0.0'
  kubernetes.core: '>=6.3.0'
  vexxhost.containers: '>=1.6.0'
tags:
  - application
  - cloud
  - infrastructure
  - linux
repository: https://github.com/vexxhost/ansible-collection-kubernetes
documentation: https://github.com/vexxhost/ansible-collection-kubernetes/tree/main/docs
homepage: https://github.com/vexxhost/ansible-collection-kubernetes
issues: https://github.com/vexxhost/ansible-collection-kubernetes/issues
build_ignore:
  - .github
  - molecule
  - .pre-commit-config.yaml
