namespace: adriacloud
name: kubernetes
version: 2.2.0
readme: README.md
authors:
  - Mohammed Naser <mnaser@vexxhost.com>
  - Dmitriy Rabotyagov <dmitriy@adria-cloud.com>
description: Fork of Vexxhost Ansible collection for deploying Kubernetes clusters
license:
  - GPL-3.0-or-later
dependencies:
  ansible.posix: ">=1.3.0"
  community.crypto: ">=2.2.3"
  community.general: ">=4.5.0"
  kubernetes.core: ">=2.3.2"
  vexxhost.containers: ">=1.3.0"
tags:
  - application
  - cloud
  - infrastructure
  - linux
repository: https://github.com/adriacloud/ansible-collection-kubernetes
documentation: https://github.com/adriacloud/ansible-collection-kubernetes/tree/main/docs
homepage: https://github.com/adriacloud/ansible-collection-kubernetes
issues: https://github.com/adriacloud/ansible-collection-kubernetes/issues
build_ignore:
  - .github
  - molecule
  - .pre-commit-config.yaml
