# Copyright (c) 2024 VEXXHOST, Inc.
# SPDX-License-Identifier: Apache-2.0

dependency:
  name: galaxy
driver:
  name: default
  options:
    managed: False
    ansible_connection_options:
      ansible_become: "true"
      ansible_connection: local
platforms:
  - name: instance
    groups:
      - controllers
provisioner:
  name: ansible
  config_options:
    connection:
      pipelining: true
    defaults:
      callbacks_enabled: ansible.posix.profile_tasks
verifier:
  name: ansible
