# Copyright (c) 2025 VEXXHOST, Inc.
# SPDX-License-Identifier: Apache-2.0

- name: Initialize the management cluster
  run_once: true
  changed_when: true
  ansible.builtin.command: |
    {{ clusterctl_download_dest }} init \
      --config {{ clusterctl_config_file }} \
      --core {{ cluster_api_core_provider }}:v{{ cluster_api_core_version }} \
      --bootstrap {{ cluster_api_bootstrap_provider }}:v{{ cluster_api_bootstrap_version }} \
      --control-plane {{ cluster_api_control_plane_provider }}:v{{ cluster_api_control_plane_version }} \
      --infrastructure {{ cluster_api_infrastructure_provider }}:v{{ cluster_api_infrastructure_version }}
  environment: "{{ _cluster_api_environment }}"
