# Copyright (c) 2025 VEXXHOST, Inc.
# SPDX-License-Identifier: Apache-2.0

---
galaxy_info:
  author: VEXXHOST, Inc.
  description: Ansible role for Kubernetes
  license: Apache-2.0
  min_ansible_version: 5.5.0
  standalone: false
  platforms:
    - name: EL
      versions:
        - "8"
        - "9"
    - name: Ubuntu
      versions:
        - focal
        - jammy

dependencies:
  - role: kubernetes_upgrade_check
  - role: kubeadm
    vars:
      kubeadm_version: "{{ kubernetes_version }}"
  - role: kubectl
    vars:
      kubectl_version: "{{ kubernetes_version }}"
  - role: kubelet
    vars:
      kubelet_version: "{{ kubernetes_version }}"
      kubelet_allow_unsafe_swap: "{{ kubernetes_allow_unsafe_swap }}"
