# Copyright (c) 2024 VEXXHOST, Inc.
# SPDX-License-Identifier: Apache-2.0

dependency:
  name: galaxy
driver:
  name: default
  options:
    managed: False
    ansible_connection_options:
      ansible_become: "true"
      ansible_connection: local
platforms:
  - name: instance
    groups:
      - controllers
provisioner:
  name: ansible
  config_options:
    connection:
      pipelining: true
  inventory:
    group_vars:
      all:
        kubernetes_version: ${KUBERNETES_VERSION-1.28.13}
        cilium_helm_values:
          operator:
            replicas: 1
      controllers:
        keepalived_interface: "{{ ansible_facts['default_ipv4'].interface }}"
        keepalived_vip: 172.17.0.100
        keepalived_vrid: 42
        kubernetes_hostname: "{{ ansible_facts['default_ipv4'].address }}"
        # use bgp for kube-vip
        kube_vip_mode: bgp
        kube_vip_bgp_routerid: 172.17.0.100
        kube_vip_bgp_routerinterface: "{{ ansible_facts['default_ipv4'].interface }}"
verifier:
  name: ansible
