# Copyright (c) 2023 VEXXHOST, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

- name: Copy without using synchronize module
  run_once: true
  block:
    - name: Ensure destination dir
      ansible.builtin.file:
        path: "{{ upload_helm_chart_dest }}"
        state: directory
        mode: "0755"
        owner: root
        group: root

    - name: Upload helm chart with multi_copy
      vexxhost.kubernetes.multi_copy:
        src: "{{ upload_helm_chart_src }}"
        dest: "{{ upload_helm_chart_dest }}"
        owner: root
        group: root
        mode: "0755"
        list_files: true
      register: multi_copy
      when: upload_helm_chart_method == 'copy'

    - name: Find destination files
      ansible.builtin.find:
        paths: "{{ upload_helm_chart_dest }}"
        recurse: true
        hidden: true
      register: destination_files

    - name: Delete any destination files not in the sources
      vars:
        s: "{{ multi_copy.files | map('regex_replace', '\\./',  '/') }}"
        d: "{{ destination_files.files | map(attribute='path') | map('regex_replace', upload_helm_chart_dest | realpath, '') }}"
      ansible.builtin.file:
        path: "{{ upload_helm_chart_dest ~ item }}"
        state: absent
      with_items: "{{ d | difference(s) }}"
