# Copyright (c) 2025 VEXXHOST, Inc.
# SPDX-License-Identifier: Apache-2.0

---
- name: Generate control-plane certificates for joining cluster
  run_once: true
  delegate_to: "{{ kubernetes_bootstrap_node | default(groups[kubernetes_control_plane_group][0]) }}"
  ansible.builtin.command: kubeadm init phase upload-certs --upload-certs
  changed_when: false
  register: kubernetes_kubeadm_init_upload_certs
  when:
    - inventory_hostname in groups[kubernetes_control_plane_group]

- name: Retrieve SHA256 certificate hash
  run_once: true
  delegate_to: "{{ kubernetes_bootstrap_node | default(groups[kubernetes_control_plane_group][0]) }}"
  community.crypto.x509_certificate_info:
    path: /etc/kubernetes/pki/ca.crt
  register: kubernetes_kubeadm_certificate_info

- name: Generate token for joining cluster
  run_once: true
  delegate_to: "{{ kubernetes_bootstrap_node | default(groups[kubernetes_control_plane_group][0]) }}"
  changed_when: true
  ansible.builtin.shell: |
    kubeadm token create
  register: kubernetes_kubeadm_token_create

- name: Upload kubeadm configuration
  ansible.builtin.template:
    src: kubeadm.yaml.j2
    dest: /etc/kubernetes/kubeadm.yaml
    owner: root
    group: root
    mode: "0640"

- name: Join cluster
  throttle: 1
  ansible.builtin.shell: |
    kubeadm join --config /etc/kubernetes/kubeadm.yaml \
                 --ignore-preflight-errors=DirAvailable--etc-kubernetes-manifests{% if kubernetes_allow_unsafe_swap %},Swap{% endif %}
  environment:
    PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
  args:
    creates: /etc/kubernetes/kubelet.conf
