# Copyright (c) 2025 VEXXHOST, Inc.
# SPDX-License-Identifier: Apache-2.0

---
- name: Check if Kubernetes is already deployed
  ansible.builtin.stat:
    path: /etc/kubernetes/kubelet.conf
  register: kubernetes_kubelet_stat

- name: Join cluster
  when: not kubernetes_kubelet_stat.stat.exists
  ansible.builtin.include_tasks: join-cluster.yml
