# Copyright (c) 2025 VEXXHOST, Inc.
# SPDX-License-Identifier: Apache-2.0

---
galaxy_info:
  author: VEXXHOST, Inc.
  description: Ansible role for "kubectl"
  license: Apache-2.0
  min_ansible_version: 5.5.0
  standalone: false
  platforms:
    - name: EL
      versions:
        - "8"
        - "9"
    - name: Ubuntu
      versions:
        - focal
        - jammy

dependencies:
  - role: vexxhost.containers.forget_package
    forget_package_name: "{{ kubectl_package_name }}"
    when: ansible_facts['pkg_mgr'] == "apt"
  - role: vexxhost.containers.download_artifact
    download_artifact_url: "{{ kubectl_download_url }}"
    download_artifact_dest: "{{ kubectl_download_dest }}"
    download_artifact_checksum: "sha256:{{ kubectl_binary_checksum }}"
    download_artifact_owner: root
    download_artifact_mode: "0755"
