# Copyright (c) 2025 VEXXHOST, Inc.
# SPDX-License-Identifier: Apache-2.0

---
ansible:
  cfg:
    defaults:
      callbacks_enabled: ansible.posix.profile_tasks
      deprecation_warnings: false
      interpreter_python: /usr/bin/python3
      strategy: serverscom.mitogen.mitogen_linear
    connection:
      pipelining: true
  executor:
    backend: ansible-playbook
    args:
      ansible_playbook:
        - --inventory=${MOLECULE_PROJECT_DIRECTORY}/inventory.yaml
