# Copyright (c) 2025 VEXXHOST, Inc.
# SPDX-License-Identifier: Apache-2.0

---
- name: Converge
  hosts: all
  become: true
  vars_files:
    - "vars/{{ cert_manager_test_version | default('default') }}.yml"
  roles:
    - vexxhost.kubernetes.helm
    - vexxhost.kubernetes.cert_manager
