# Copyright (c) 2026 VEXXHOST, Inc.
# SPDX-License-Identifier: Apache-2.0

---
- name: Verify
  hosts: all
  become: true
  vars:
    cert_manager_helm_release_name: cert-manager
    cert_manager_helm_release_namespace: cert-manager
  tasks:
    - name: Get Helm release info
      kubernetes.core.helm_info:
        name: "{{ cert_manager_helm_release_name }}"
        release_namespace: "{{ cert_manager_helm_release_namespace }}"
        kubeconfig: /etc/kubernetes/admin.conf
      register: _cert_manager_release

    - name: Get cert-manager pods
      kubernetes.core.k8s_info:
        kind: Pod
        namespace: "{{ cert_manager_helm_release_namespace }}"
        kubeconfig: /etc/kubernetes/admin.conf
      register: _cert_manager_pods

    - name: Assert cert-manager release is healthy
      ansible.builtin.assert:
        that:
          - _cert_manager_release.status.status | lower == "deployed"

    - name: Assert cert-manager pods are running
      ansible.builtin.assert:
        that:
          - _cert_manager_pods.resources | length > 0
          - _cert_manager_pods.resources | selectattr('status.phase', 'equalto', 'Running') | list | length == _cert_manager_pods.resources | length
        fail_msg: "Not all cert-manager pods are running"
