# Copyright (c) 2024 VEXXHOST, Inc.
# SPDX-License-Identifier: Apache-2.0

dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: geerlingguy/docker-${MOLECULE_DISTRO:-debian13}-ansible
    pre_build_image: true
    override_command: false
    privileged: true
    cgroupns_mode: host
    tmpfs:
      - /var/lib/containerd
    volumes:
      - /boot:/boot:ro
      - /lib/modules:/lib/modules:ro
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    groups:
      - controllers
provisioner:
  name: ansible
  config_options:
    connection:
      pipelining: true
  inventory:
    group_vars:
      all:
        kubernetes_version: ${KUBERNETES_VERSION-1.28.13}
        cilium_helm_values:
          operator:
            replicas: 1
      controllers:
        keepalived_interface: "{{ ansible_facts['default_ipv4'].interface }}"
        keepalived_vip: 172.17.0.100
        keepalived_vrid: 42
        kubernetes_hostname: "{{ ansible_facts['default_ipv4'].address }}"
verifier:
  name: ansible
