# Copyright (c) 2025 VEXXHOST, Inc.
# SPDX-License-Identifier: Apache-2.0

- name: Deploy Helm chart
  run_once: true
  kubernetes.core.helm:
    name: "{{ cert_manager_helm_release_name }}"
    chart_ref: "{{ cert_manager_helm_chart_ref }}"
    release_namespace: "{{ cert_manager_helm_release_namespace }}"
    create_namespace: true
    kubeconfig: /etc/kubernetes/admin.conf
    values: "{{ _cert_manager_helm_values | combine(cert_manager_helm_values, recursive=True) }}"
