# Copyright (c) 2025 VEXXHOST, Inc.
# SPDX-License-Identifier: Apache-2.0

_cert_manager_helm_values:
  installCRDs: true
  global:
    leaderElection:
      namespace: "{{ cert_manager_helm_release_namespace }}"
  featureGates: AdditionalCertificateOutputFormats=true
  image:
    repository: "{{ cert_manager_image_controller | vexxhost.kubernetes.docker_image('name') }}"
    tag: "{{ cert_manager_image_controller | vexxhost.kubernetes.docker_image('tag') }}"
  volumes:
    - name: etc-ssl-certs
      hostPath:
        path: "{{ '/etc/ssl/certs' if ansible_facts['os_family'] in ['Debian'] else '/etc/pki/ca-trust/extracted/openssl' }}"
  volumeMounts:
    - name: etc-ssl-certs
      mountPath: /etc/ssl/certs
      readOnly: true
  nodeSelector: "{{ cert_manager_node_selector }}"
  webhook:
    extraArgs:
      - --feature-gates=AdditionalCertificateOutputFormats=true
    nodeSelector: "{{ cert_manager_node_selector }}"
    image:
      repository: "{{ cert_manager_image_webhook | vexxhost.kubernetes.docker_image('name') }}"
      tag: "{{ cert_manager_image_webhook | vexxhost.kubernetes.docker_image('tag') }}"
  cainjector:
    nodeSelector: "{{ cert_manager_node_selector }}"
    image:
      repository: "{{ cert_manager_image_cainjector | vexxhost.kubernetes.docker_image('name') }}"
      tag: "{{ cert_manager_image_cainjector | vexxhost.kubernetes.docker_image('tag') }}"
  startupapicheck:
    nodeSelector: "{{ cert_manager_node_selector }}"
    image:
      repository: "{{ cert_manager_image_cli | vexxhost.kubernetes.docker_image('name') }}"
      tag: "{{ cert_manager_image_cli | vexxhost.kubernetes.docker_image('tag') }}"
  acmesolver:
    image:
      repository: "{{ cert_manager_image_acmesolver | vexxhost.kubernetes.docker_image('name') }}"
      tag: "{{ cert_manager_image_acmesolver | vexxhost.kubernetes.docker_image('tag') }}"
