# Copyright (c) 2026 VEXXHOST, Inc.
# SPDX-License-Identifier: Apache-2.0

---
cert_manager_image_startupapicheck: "quay.io/jetstack/cert-manager-startupapicheck:{{ cert_manager_image_tag }}"

_cert_manager_version_values:
  extraArgs:
    - --enable-gateway-api
  startupapicheck:
    image:
      repository: "{{ cert_manager_image_startupapicheck | vexxhost.kubernetes.docker_image('name') }}"
      tag: "{{ cert_manager_image_startupapicheck | vexxhost.kubernetes.docker_image('tag') }}"
