name: bump

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: write
  pull-requests: write

jobs:
  kubernetes:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@8d3c67de8e2fe68ef647c8db1e6a09f647780f40 # v2.19.0
        with:
          egress-policy: audit

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          token: ${{ secrets.VEXXHOST_BOT_PAT }}
      - run: ./hack/bump/kubernetes.sh
        env:
          GH_TOKEN: ${{ github.token }}
      - uses: step-security/create-pull-request@e604d57b37b404d8bb34d152fa905e45d003a895 # v8.1.0
        with:
          token: ${{ secrets.VEXXHOST_BOT_PAT }}
          push-to-fork: vexxhost-bot/ansible-collection-kubernetes
          commit-message: "chore(deps): update kubernetes"
          signoff: true
          branch: bump/kubernetes
          delete-branch: true
          title: "chore(deps): update kubernetes"
          body: |
            ## Automated `kubernetes` update

            This PR updates the `kubernetes` binaries to the latest versions.
