# Copyright (c) 2025 VEXXHOST, Inc.
# SPDX-License-Identifier: Apache-2.0

name: ci

on:
  pull_request:
  push:
    branches: [main]

permissions: {}

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0
      - uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd # v3.0.1

  ansible-test:
    runs-on: ubuntu-latest
    permissions:
      checks: write
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: astral-sh/setup-uv@4959332f0f014c5280e7eac8b70c90cb574c9f9b # v6.6.0
      - run: uv run ansible-galaxy collection install .
      - run: uv run ansible-test units --python $(cat .python-version)
        working-directory: /home/runner/.ansible/collections/ansible_collections/vexxhost/kubernetes
      - uses: mikepenz/action-junit-report@3585e9575db828022551b4231f165eb59a0e74e3 # v5.6.2
        if: always()
        with:
          report_paths: /home/runner/.ansible/collections/ansible_collections/vexxhost/kubernetes/tests/output/junit/*.xml

  molecule:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        distro:
          - debian13
          - rockylinux9
          - ubuntu2004
          - ubuntu2204
          - ubuntu2404
        scenario:
          - aio
          # - bgp
          # - cluster-api
          # - cluster-api-upgrade
          # - ha
        kubernetes-version:
          - 1.26.15
          - 1.27.16
          - 1.28.13
          - 1.29.12
          - 1.30.8
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: astral-sh/setup-uv@4959332f0f014c5280e7eac8b70c90cb574c9f9b # v6.6.0
      - run: sudo swapoff -a
      - run: uv run molecule test --destroy never -s ${{ matrix.scenario }}
        env:
          MOLECULE_DISTRO: ${{ matrix.distro }}
          KUBERNETES_VERSION: ${{ matrix.kubernetes-version }}
