# Copyright (c) 2025 VEXXHOST, Inc.
# SPDX-License-Identifier: Apache-2.0

name: ci

on:
  pull_request:
  push:
    branches: [main]

permissions: {}

jobs:
  ansible-test:
    runs-on: ubuntu-latest
    permissions:
      checks: write
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: astral-sh/setup-uv@bd01e18f51369d5a26f1651c3cb451d3417e3bba # v6.3.1
      - run: uv run ansible-galaxy collection install .
      - run: uv run ansible-test units
        working-directory: /home/runner/.ansible/collections/ansible_collections/vexxhost/kubernetes
      - uses: mikepenz/action-junit-report@3585e9575db828022551b4231f165eb59a0e74e3 # v5.6.2
        if: always()
        with:
          report_paths: /home/runner/.ansible/collections/ansible_collections/vexxhost/kubernetes/tests/output/junit/*.xml
