name: docs

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Install Earthly
        uses: earthly/actions-setup@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image
        run: earthly --secret GITHUB_TOKEN +mkdocs-build
        env:
          EARTHLY_CI: true
          EARTHLY_PUSH: "${{ github.event_name == 'push' }}"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
